apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-petclinic
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/YuriiDiduk/ArgoCD-pet-config2.git
    targetRevision: HEAD
    path: app
  destination: 
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    syncOptions:
    - CreateNamespace=false

    automated:
      selfHeal: true
      prune: true
