apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqlp
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqlp
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysqlp
    spec:
      containers:
        - name: mysqlp
          image: mysql:5.7
          ports:
            - name: sql
              containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: petclinic
            - name: MYSQL_DATABASE
              value: petclinic
---
apiVersion: v1
kind: Service
metadata:
  name: mysqlp
  namespace: prod
spec:
  type: NodePort
  selector:
    app: mysqlp 

  ports:
    - name: sql
      port: 3306
      protocol: TCP
      targetPort: 3306
      nodePort: 30036

