apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-petclinic
  template:
    metadata:
      labels:
        app: spring-petclinic
    spec:
      containers:
        - name: spring-petclinic
          image: st251/petclinic:50
          ports:
            - name: web
              containerPort: 8181
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: mysql
            - name: URL
              value: mysqlp
 







