apiVersion: v1
kind: Service
metadata:
  name: mysqlp
  namespace: prod
spec:
  type: NodePort
  selector:
    app: mysqlp 

  ports:
    - name: sql
      port: 3306
      protocol: TCP
      targetPort: 3306
      nodePort: 30036
