apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


patchesStrategicMerge:
- custom-env.yaml
- replica-and-rollout-strategy.yaml
- database-secret.yaml
resources:
- ../../base
secretGenerator:
- literals:
  - db-password=12345
  name: sl-demo-app
  type: Opaque
images:
- name: foo/bar
  newName: foo/bar
  newTag: "34"
